hansung-pocs/blog-android

presentation/src/androidTest/java/com/pocs/presentation/UserDetailScreenTest.kt
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/pocs/presentation/mapper/UserMapper.kt
presentation/src/main/java/com/pocs/presentation/mock/Mocks.kt
presentation/src/main/java/com/pocs/presentation/model/UserDetailItemUiState.kt
presentation/src/main/java/com/pocs/presentation/model/UserDetailUiState.kt
presentation/src/main/java/com/pocs/presentation/model/UserItemUiState.kt
presentation/src/main/java/com/pocs/presentation/view/common/AppBarBackButton.kt
presentation/src/main/java/com/pocs/presentation/view/common/FailureContent.kt
presentation/src/main/java/com/pocs/presentation/view/common/LoadingContent.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserAdapter.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserListFragment.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserViewHolder.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailViewModel.kt
presentation/src/main/res/layout/item_user.xml
presentation/src/main/res/values/strings.xml

UserDetail 페이지 구현

---

data/src/main/java/com/pocs/data/api/UserApi.kt
data/src/main/java/com/pocs/data/di/RemoteModule.kt
data/src/main/java/com/pocs/data/di/RepositoryModule.kt
data/src/main/java/com/pocs/data/mapper/UserMapper.kt
data/src/main/java/com/pocs/data/repository/UserRepositoryImpl.kt
data/src/main/java/com/pocs/data/source/UserRemoteDataSource.kt
data/src/main/java/com/pocs/data/source/UserRemoteDataSourceImpl.kt
domain/src/main/java/com/pocs/domain/model/user/UserType.kt
presentation/src/main/java/com/pocs/presentation/mock/Mocks.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailViewModel.kt
presentation/src/test/java/com/pocs/presentation/UserDetailViewModelTest.kt
test-library/src/main/java/com/pocs/test_library/fake/FakeUserRepositoryImpl.kt

Resolves #32 
**기타 사항**
- UserType에 `UNKNOWN`을 추가했습니다.

UserDetail API 구현 및 연결

---

presentation/build.gradle
presentation/src/main/java/com/pocs/presentation/extension/ContentLoadStateBindingExt.kt
presentation/src/main/java/com/pocs/presentation/view/admin/post/AdminPostFragment.kt
presentation/src/main/java/com/pocs/presentation/view/admin/user/AdminUserFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/article/ArticleFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/notice/NoticeFragment.kt
presentation/src/main/java/com/pocs/presentation/view/post/by/user/PostByUserActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserFragment.kt
presentation/src/main/res/layout/activity_post_by_user.xml
presentation/src/main/res/layout/fragment_admin_user.xml
presentation/src/main/res/layout/fragment_post.xml
presentation/src/main/res/layout/fragment_user.xml

Resolves #97 
페이징 어뎁터를 이용하는 모든 리사이클러뷰에 구현했습니다.

당겨서 새로고침 기능 추가

---

domain/src/main/java/com/pocs/domain/usecase/user/GetCurrentUserDetailUseCase.kt
domain/src/main/java/com/pocs/domain/usecase/user/GetMyUserInfoUseCase.kt
presentation/src/main/java/com/pocs/presentation/model/post/HomeUiState.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeViewModel.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserViewHolder.kt
presentation/src/main/res/drawable/ic_baseline_edit_24.xml
presentation/src/main/res/menu/menu_drawer.xml

Resolves #95 
- HomeVIewModel 와 GetMyInfoUseCase 추가하였습니다.

홈 Drawer메뉴에 "내 정보 수정" 추가 및 기능 구현

---

presentation/src/main/java/com/pocs/presentation/extension/ContentLoadStateBindingExt.kt
presentation/src/main/java/com/pocs/presentation/view/admin/post/AdminPostFragment.kt
presentation/src/main/java/com/pocs/presentation/view/admin/user/AdminUserFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/article/ArticleFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/notice/NoticeFragment.kt
presentation/src/main/java/com/pocs/presentation/view/post/by/user/PostByUserActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserFragment.kt

Resolves #108 
데모때 보였던 기능을 실제로 추가했습니다.
`ContentLoadStateBinding.setListeners`가 너무 비대해져 하나의 함수에서 너무 많은 기능을 수행하지 않는지 고민됩니다.
https://user-images.githubusercontent.com/57604817/183233135-c2ac053a-16c3-4895-8040-3471d87a9865.mov

리사이클러 뷰에서 항목이 추가되면 맨 위로 스크롤 하도록 수정

---

presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
presentation/src/main/res/drawable/ic_baseline_account_circle_24.xml
presentation/src/main/res/menu/menu_drawer.xml
presentation/src/main/res/menu/menu_home.xml
presentation/src/main/res/values/strings.xml

Resolves #116
- 전에 있던 menu_home에서 settings를 삭제하였습니다. 
- 이와 관련이 있던 코드부분 layout menu 또한 삭제하였습니다.
- drawer에서 내 정보 수정와 관련된 코드부분 삭제하였습니다.
- HomeViewModel 에서는 크게 변화없이 우선 HomeActivity에서 Id만 불러오도록 변수를 수정하였습니다.

홈 화면 내 상세 정보 바로가기 아이콘 생성 및 기능 구현

---

presentation/src/main/java/com/pocs/presentation/view/component/dialog/PasswordDialog.kt

비밀번호 dialog 키보드 엔터키를 send로 수정

---

presentation/src/androidTest/java/com/pocs/presentation/PostEditActivityTest.kt
presentation/src/androidTest/java/com/pocs/presentation/PostEditScreenTest.kt
presentation/src/androidTest/java/com/pocs/presentation/extension/ComposeRuleExt.kt

Fixes #121 
https://issuetracker.google.com/issues/217880227 참고함
https://developer.android.com/jetpack/compose/testing?hl=ko#disable-autosync  -> auto advance 참고

불안정한 테스트 수정

---

build.gradle
data/build.gradle
presentation/build.gradle
presentation/src/main/java/com/pocs/presentation/view/component/appbar/EditContentAppBar.kt
presentation/src/main/java/com/pocs/presentation/view/component/dialog/PasswordDialog.kt
presentation/src/main/java/com/pocs/presentation/view/component/textfield/PocsOutlineTextField.kt
presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
test-library/build.gradle
test-library/src/main/java/com/pocs/test_library/rule/JodaRule.kt

resolves #128 
- compose, fragment, navigation, kotlin 버전을 업데이트했습니다.

의존성들 버전 업데이트

---

presentation/src/main/java/com/pocs/presentation/base/ViewBindingActivity.kt
presentation/src/main/java/com/pocs/presentation/base/ViewBindingFragment.kt
presentation/src/main/java/com/pocs/presentation/view/admin/AdminActivity.kt
presentation/src/main/java/com/pocs/presentation/view/admin/post/AdminPostFragment.kt
presentation/src/main/java/com/pocs/presentation/view/admin/user/AdminUserFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
presentation/src/main/java/com/pocs/presentation/view/home/article/ArticleFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/notice/NoticeFragment.kt
presentation/src/main/java/com/pocs/presentation/view/post/by/user/PostByUserActivity.kt
presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserFragment.kt

Resolves #130 
이제 뷰바인딩이 필요한 엑티비티와 프레그먼트는 `ViewBindingXXX`를 상속하여 구현하면 됩니다.
https://stackoverflow.com/questions/62407823/how-using-viewbinding-with-an-abstract-base-class/65166784#65166784 을 참고하여 구현했습니다.

ViewBindingXXX pattern 적용

---

domain/src/test/java/com/pocs/domain/CanDeletePostUseCaseTest.kt
domain/src/test/java/com/pocs/domain/CanEditPostUseCaseTest.kt
presentation/src/test/java/com/pocs/presentation/UserDetailViewModelTest.kt
test-library/src/main/java/com/pocs/test_library/mock/Post.kt

모델의 빈 값을 `-`으로 사용하던 테스트 코드 수정

---

data/src/main/java/com/pocs/data/repository/UserRepositoryImpl.kt
domain/src/main/java/com/pocs/domain/usecase/user/IsCurrentUserAdminUseCase.kt
domain/src/main/java/com/pocs/domain/usecase/user/IsCurrentUserUnknownUseCase.kt
domain/src/test/java/com/pocs/domain/IsCurrentUserAdminUseCaseTest.kt
domain/src/test/java/com/pocs/domain/IsCurrentUserUnknownUseCaseTest.kt
presentation/src/androidTest/java/com/pocs/presentation/UserDetailActivityTest.kt
presentation/src/main/java/com/pocs/presentation/model/ArticleUiState.kt
presentation/src/main/java/com/pocs/presentation/model/NoticeUiState.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeViewModel.kt
presentation/src/main/java/com/pocs/presentation/view/home/article/ArticleFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/article/ArticleViewModel.kt
presentation/src/main/java/com/pocs/presentation/view/home/notice/NoticeFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/notice/NoticeViewModel.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailViewModel.kt
presentation/src/main/res/menu/menu_drawer.xml
presentation/src/test/java/com/pocs/presentation/ArticleViewModelTest.kt
presentation/src/test/java/com/pocs/presentation/HomeViewModelTest.kt
presentation/src/test/java/com/pocs/presentation/NoticeViewModelTest.kt
presentation/src/test/java/com/pocs/presentation/UserDetailViewModelTest.kt

Resolves #39 
- 관리자만 공지 쓰기 버튼 보이도록 함
- 회원이 아닌 경우 게시글 쓰기 버튼 안보이도록 함
- 관리자만 관리자 메뉴 보이도록 함
- 코드 리팩토링

현재 유저 타입에 따라 특정 기능 접근 못하도록 수정

---

presentation/src/androidTest/java/com/pocs/presentation/UserDetailActivityTest.kt
presentation/src/androidTest/java/com/pocs/presentation/UserDetailScreenTest.kt
presentation/src/main/java/com/pocs/presentation/model/user/UserDetailUiState.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailViewModel.kt
presentation/src/test/java/com/pocs/presentation/UserDetailViewModelTest.kt

내정보가 아니면 내정보 수정 버튼 보이지 않도록 수정

---

data/src/main/java/com/pocs/data/repository/AuthRepositoryImpl.kt
domain/build.gradle
domain/src/main/java/com/pocs/domain/repository/AuthRepository.kt
domain/src/main/java/com/pocs/domain/usecase/auth/LogoutUseCase.kt
domain/src/main/java/com/pocs/domain/usecase/user/UpdateUserUseCase.kt
domain/src/test/java/com/pocs/domain/UpdateUserUseCaseTest.kt
presentation/src/androidTest/java/com/pocs/presentation/SettingViewModelTest.kt
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/pocs/presentation/model/post/HomeUiState.kt
presentation/src/main/java/com/pocs/presentation/model/setting/SettingUiState.kt
presentation/src/main/java/com/pocs/presentation/view/component/PocsDivider.kt
presentation/src/main/java/com/pocs/presentation/view/component/RecheckHandler.kt
presentation/src/main/java/com/pocs/presentation/view/component/button/PocsButton.kt
presentation/src/main/java/com/pocs/presentation/view/component/textfield/PasswordOutlineTextField.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeViewModel.kt
presentation/src/main/java/com/pocs/presentation/view/login/LoginActivity.kt
presentation/src/main/java/com/pocs/presentation/view/login/LoginScreen.kt
presentation/src/main/java/com/pocs/presentation/view/login/LoginViewModel.kt
presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
presentation/src/main/java/com/pocs/presentation/view/setting/SettingActivity.kt
presentation/src/main/java/com/pocs/presentation/view/setting/SettingScreen.kt
presentation/src/main/java/com/pocs/presentation/view/setting/SettingViewModel.kt
presentation/src/main/res/menu/menu_home.xml
presentation/src/main/res/values/strings.xml
presentation/src/test/java/com/pocs/presentation/HomeViewModelTest.kt
test-library/src/main/java/com/pocs/test_library/fake/FakeAuthRepositoryImpl.kt
test-library/src/main/java/com/pocs/test_library/fake/FakeUserRepositoryImpl.kt

설정화면 및 로그아웃 UI 구현

---

presentation/src/androidTest/java/com/pocs/presentation/LoginScreenTest.kt
presentation/src/main/java/com/pocs/presentation/model/auth/LoginUiState.kt
presentation/src/main/java/com/pocs/presentation/view/component/button/PocsButton.kt
presentation/src/main/java/com/pocs/presentation/view/login/LoginScreen.kt

Resolves #147 
아이디, 비밀번호 모두 입력해야 로그인 버튼을 활성화 하도록 수정했습니다.

로그인 내용을 모두 입력해야 로그인 버튼 활성화하도록 수정

---

presentation/src/main/java/com/pocs/presentation/view/setting/SettingScreen.kt

사용자에게 누르면 정보가 있다는 느낌을 전달하기 위해서 아이콘을 추가했습니다.
|전|후|
|---|---|
|![스크린샷 2022-08-12 오전 11 41 27](https://user-images.githubusercontent.com/57604817/184275177-90ea6527-5ba2-4d15-ac8f-fabf7bd067c7.png)|![스크린샷 2022-08-12 오전 11 40 47](https://user-images.githubusercontent.com/57604817/184275200-280afa4c-849c-47fa-934b-6f160d0b3a85.png)|

설정 화면에서 오른쪽 화살표 아이콘 추가

---

presentation/src/main/java/com/pocs/presentation/view/login/LoginActivity.kt
presentation/src/main/java/com/pocs/presentation/view/login/LoginViewModel.kt
presentation/src/test/java/com/pocs/presentation/LoginViewModelTest.kt

#153 에서 구현한 코드의 가독성을 향상했습니다. 추가로 필요없는 코드도 제거했습니다.

자동 로그인 코드 개선

---

data/build.gradle
data/src/main/java/com/pocs/data/di/LocalModule.kt

Resolves #158 
https://striban.tistory.com/66 방법을 이용하여 암호화 하도록 했습니다.

로컬에 세션 토큰 저장 시 암호화 하여 저장하도록 수정

---

data/src/main/java/com/pocs/data/api/PostApi.kt
data/src/main/java/com/pocs/data/mapper/PostFilterTypeMapper.kt
data/src/main/java/com/pocs/data/model/post/PostListDto.kt
data/src/main/java/com/pocs/data/paging/AdminPostByUserPagingSource.kt
data/src/main/java/com/pocs/data/paging/AdminPostPagingSource.kt
data/src/main/java/com/pocs/data/paging/PostPagingSource.kt
data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt
data/src/main/java/com/pocs/data/source/PostRemoteDataSource.kt
data/src/main/java/com/pocs/data/source/PostRemoteDataSourceImpl.kt
domain/src/main/java/com/pocs/domain/model/post/PostCategory.kt
presentation/src/main/java/com/pocs/presentation/extension/PostExt.kt
presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
test-library/src/main/java/com/pocs/test_library/fake/source/remote/FakePostRemoteDataSource.kt

게시글 카테고리 별로 요청하는 API 구현

---

data/src/main/java/com/pocs/data/mapper/PostDetailMapper.kt
data/src/main/java/com/pocs/data/mapper/PostMapper.kt
data/src/main/java/com/pocs/data/model/post/PostDetailDto.kt
data/src/main/java/com/pocs/data/model/post/PostDto.kt
domain/src/main/java/com/pocs/domain/model/post/Post.kt
domain/src/main/java/com/pocs/domain/model/post/PostDetail.kt
domain/src/test/java/com/pocs/domain/CanDeletePostUseCaseTest.kt
domain/src/test/java/com/pocs/domain/CanEditPostUseCaseTest.kt
presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
presentation/src/main/java/com/pocs/presentation/mapper/PostDetailMapper.kt
presentation/src/main/java/com/pocs/presentation/model/post/item/PostDetailItemUiState.kt
presentation/src/main/java/com/pocs/presentation/view/component/Comments.kt
presentation/src/main/java/com/pocs/presentation/view/component/Label.kt
presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
presentation/src/main/res/values/strings.xml
test-library/src/main/java/com/pocs/test_library/mock/Post.kt

게시글 조회수 구현

---

data/src/main/java/com/pocs/data/api/AdminApi.kt
data/src/main/java/com/pocs/data/api/PostApi.kt
data/src/main/java/com/pocs/data/api/UserApi.kt
data/src/main/java/com/pocs/data/model/post/PostListDto.kt
data/src/main/java/com/pocs/data/paging/AdminPostByUserPagingSource.kt
data/src/main/java/com/pocs/data/paging/AdminPostPagingSource.kt
data/src/main/java/com/pocs/data/paging/AdminUserPagingSource.kt
data/src/main/java/com/pocs/data/paging/PostPagingSource.kt
data/src/main/java/com/pocs/data/paging/UserPagingSource.kt
data/src/main/java/com/pocs/data/repository/AdminRepositoryImpl.kt
data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt
data/src/main/java/com/pocs/data/repository/UserRepositoryImpl.kt

백엔드 팀에서 페이지네이션을 구현함에 따라 안드로이드에서도 페이지네이션을 적용하였습니다.
현재는 pageSize를 30으로 두었지만 B팀과의 협의를 통해서 수정될 수 있습니다.

페이지네이션 API 기능 구현 

---

presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
presentation/src/main/java/com/pocs/presentation/view/component/AppBar.kt
presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt

https://user-images.githubusercontent.com/57604817/185741574-38968605-efe1-463d-b477-605f3c880e64.mov

PostDetailScreen에 스크롤하면 앱바에 제목이 보이는 기능 구현

---

data/src/main/java/com/pocs/data/mapper/PostWriterMapper.kt
data/src/main/java/com/pocs/data/model/comment/CommentWriterDto.kt
data/src/main/java/com/pocs/data/model/post/PostWriterDto.kt
domain/src/main/java/com/pocs/domain/model/comment/CommentWriter.kt
domain/src/main/java/com/pocs/domain/model/post/PostCategory.kt
domain/src/main/java/com/pocs/domain/model/post/PostWriter.kt
presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
presentation/src/androidTest/java/com/pocs/presentation/PostFragmentTest.kt
presentation/src/main/java/com/pocs/presentation/model/comment/item/CommentWriterUiState.kt
presentation/src/main/java/com/pocs/presentation/model/post/item/PostWriterUiState.kt
presentation/src/main/java/com/pocs/presentation/model/study/StudyUiState.kt
presentation/src/main/java/com/pocs/presentation/view/component/Comments.kt
presentation/src/main/java/com/pocs/presentation/view/component/markdown/MarkdownText.kt
presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/study/StudyFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/study/StudyViewModel.kt
presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
presentation/src/main/res/values/strings.xml

임시로 PostWriter의 name, email을 nullable로 바꾸고 이름이 널인경우 "익명"으로 표현하도록 수정했습니다.

질문답변 게시글 상세조회 에러 수정

---

presentation/src/androidTest/java/com/pocs/presentation/HomeActivityTest.kt
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/pocs/presentation/model/post/HomeUiState.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
presentation/src/main/java/com/pocs/presentation/view/home/HomeViewModel.kt
presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
presentation/src/main/java/com/pocs/presentation/view/home/study/StudyFragment.kt

Fixes #196 
FAB가 안보일때는 HomeActivity에서 메시지를 띄우도록 하여 해결했습니다.

홈화면에서 FAB가 안보일때 스낵바 위치 이상하던 문제 해결

---

presentation/src/androidTest/java/com/pocs/presentation/PostDetailActivityTest.kt
presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
presentation/src/androidTest/java/com/pocs/presentation/comment/CommentTest.kt
presentation/src/main/java/com/pocs/presentation/model/comment/CommentsUiState.kt
presentation/src/main/java/com/pocs/presentation/model/post/PostDetailUiState.kt
presentation/src/main/java/com/pocs/presentation/view/component/Comments.kt
presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailViewModel.kt
presentation/src/main/res/values/strings.xml

익명회원은 본인이 작성한 QnA 게시글 외에는 댓글 작성할 수 없도록 수정

---

presentation/src/main/java/com/pocs/presentation/view/home/study/StudyFragment.kt

스터디 탭에서는 게시글 작성시 기본 타입이 "스터디"이도록 수정

---

presentation/src/androidTest/java/com/pocs/presentation/AdminUserFragmentTest.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserViewHolder.kt

Fixes #229 
문제가 있던 테스트를 수정했습니다.

불안정한 AdminUserFragment 테스트 수정

---

presentation/src/main/java/com/pocs/presentation/extension/ContentLoadStateBindingExt.kt
presentation/src/main/res/layout/content_load_state.xml

Resolves #236 
ProgressBar를 제거하고 로딩중에는 SwipeToRefresh만 보이도록 했습니다.

ProgressBar 삭제

---

presentation/src/androidTest/java/com/pocs/presentation/SearchAppBarTest.kt
presentation/src/main/java/com/pocs/presentation/constant/UserConstant.kt
presentation/src/main/java/com/pocs/presentation/view/component/appbar/SearchAppBar.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserViewModel.kt

Resolves #238 
- padding 안맞던 문제 해결
- [debounce](https://velog.io/@ansrjsdn/Debounce란) 구현
https://user-images.githubusercontent.com/57604817/187816768-0ab8c2a5-e47b-4661-bbb8-285297cda4c8.mov
https://user-images.githubusercontent.com/57604817/187816620-6071aace-d3fb-4739-8c34-3dd806916cb3.mov

유저 검색화면 개선

---

data/src/main/java/com/pocs/data/model/user/UserUpdateBody.kt
data/src/main/java/com/pocs/data/repository/UserRepositoryImpl.kt
data/src/main/java/com/pocs/data/source/UserRemoteDataSource.kt
data/src/main/java/com/pocs/data/source/UserRemoteDataSourceImpl.kt
domain/src/main/java/com/pocs/domain/repository/UserRepository.kt
domain/src/main/java/com/pocs/domain/usecase/user/UpdateUserUseCase.kt
presentation/src/androidTest/java/com/pocs/presentation/UserEditScreenTest.kt
presentation/src/main/java/com/pocs/presentation/model/user/UserEditUiState.kt
presentation/src/main/java/com/pocs/presentation/view/component/textfield/PasswordOutlineTextField.kt
presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditScreen.kt
presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditViewModel.kt
test-library/src/main/java/com/pocs/test_library/fake/FakeUserRepositoryImpl.kt
test-library/src/main/java/com/pocs/test_library/fake/source/remote/FakeUserRemoteDataSource.kt

유저 정보 수정에서 비밀번호를 확인용이 아니라 변경용도으로 수정

---

presentation/src/main/java/com/pocs/presentation/view/component/appbar/SearchAppBar.kt

다크 모드에서 SearchAppBar 텍스트 잘 안보이던 문제 해결

---

presentation/src/main/java/com/pocs/presentation/view/post/adapter/PostViewHolder.kt
presentation/src/main/res/layout/item_post.xml

Resolves #266 
|수정 전|수정 후|
|---|---|
|![image](https://user-images.githubusercontent.com/57604817/190890209-30527dac-9de5-47bb-9ff2-9bd65a9d8d6b.png)|![image](https://user-images.githubusercontent.com/57604817/190890344-2fc59afd-b1ee-4820-8890-9f15b38cc7d1.png)|

PostViewHodler UI 수정

---

presentation/src/main/java/com/pocs/presentation/extension/IntentExt.kt
presentation/src/main/java/com/pocs/presentation/view/admin/AdminActivity.kt
presentation/src/main/java/com/pocs/presentation/view/post/by/user/PostByUserActivity.kt
presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateActivity.kt
presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditScreen.kt

Resolves #247 
- onBackPressed 수정
- getSerializableExtra 수정
- 그 외 제대로 사용하는 부분은 경고가 나오지 않도록 suppress 함

Deprecated API들 수정

---

data/src/main/java/com/pocs/data/model/auth/LoginRequestBody.kt
data/src/main/java/com/pocs/data/repository/AuthRepositoryImpl.kt

Login API 요청 키 값 변경 대응

---

presentation/src/main/res/values/strings.xml

앱이름 POCS로 변경

---

presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt

Resolves #279 
|Before|After|
|---|---|
|![스크린샷 2022-09-24 오후 9 56 23](https://user-images.githubusercontent.com/57604817/192099170-feb37fb9-6654-4579-999c-a0e37746bfd7.png)|![스크린샷 2022-09-24 오후 9 56 00](https://user-images.githubusercontent.com/57604817/192099176-b1a2f346-c743-468b-b4a3-eb97e72dd738.png)|

UserDetailScreen UI 수정

---

data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt

API에서 게시글 수정 성공 시 응답코드가 기존 302에서 200으로 변경되었습니다. 이에 대응하였습니다.

Post Update API Response 응답 코드 수정 대응

---

android.gradle
data/src/main/java/com/pocs/data/mapper/UserDefaultInfoMapper.kt

추가로 GitHub Secret Key에 있는 SERVER_URL까지 수정했습니다.

배포 서버와 개발 서버 url을 다르게 하도록 수정

---

data/src/main/java/com/pocs/data/di/RemoteModule.kt
data/src/main/java/com/pocs/data/di/RepositoryModule.kt

단순 리팩토링입니다. https://developer.android.com/training/dependency-injection/hilt-android?hl=ko#inject-interfaces 
방법을 참고하여 코드를 간소화 해봤습니다.

DI module에서 Binds annotation으로 교체

---

build.gradle
presentation/build.gradle
presentation/src/main/java/com/pocs/presentation/view/admin/user/create/AdminUserCreateActivity.kt
presentation/src/main/java/com/pocs/presentation/view/component/PocsDivider.kt
presentation/src/main/java/com/pocs/presentation/view/component/appbar/EditContentAppBar.kt
presentation/src/main/java/com/pocs/presentation/view/component/appbar/SearchAppBar.kt
presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
presentation/src/main/java/com/pocs/presentation/view/login/LoginActivity.kt
presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateActivity.kt
presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailActivity.kt
presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditActivity.kt
presentation/src/main/java/com/pocs/presentation/view/setting/SettingActivity.kt
presentation/src/main/java/com/pocs/presentation/view/setting/SettingScreen.kt
presentation/src/main/java/com/pocs/presentation/view/user/UserActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailActivity.kt
presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditActivity.kt

Fixes #295 
컴포즈 의존성 버전을 올려 댓글 입력창 문제를 해결했습니다.
컴포즈 버전을 올림으로 인해 필요한 마이그레이션을 추가로 진행했습니다.

Migrate compose versions
