- presentation/src/androidTest/java/com/pocs/presentation/PostEditScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/model/BasePostEditUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
- presentation/src/main/res/values/strings.xml
Resolves #57 
다음과 같은 경우에 AlertDialog를 보입니다.
- 제목 혹은 글 내용이 작성되어 있을 때 뒤로가기(앱바의 버튼 혹은 기기의 뒤로가기 버튼)를 누른 경우
다음과 같은 경우에 보이지 **않습니다.**
- 제목과 글 내용 모두 비어있는 경우
- 포스트를 저장할 때
> Post 편집할 때 뒤로가기를 누른 경우 다시 확인하는 다이어로그 보이도록 수정

- data/src/main/java/com/pocs/data/api/AdminApi.kt
- data/src/main/java/com/pocs/data/mapper/UserCreateInfoMapper.kt
- data/src/main/java/com/pocs/data/mapper/UserTypeMapper.kt
- data/src/main/java/com/pocs/data/model/admin/UserCreateInfoBody.kt
- data/src/main/java/com/pocs/data/repository/AdminRepositoryImpl.kt
- data/src/main/java/com/pocs/data/source/AdminRemoteDataSource.kt
- data/src/main/java/com/pocs/data/source/AdminRemoteDataSourceImpl.kt
- domain/src/main/java/com/pocs/domain/model/admin/UserCreateInfo.kt
- domain/src/main/java/com/pocs/domain/model/user/UserType.kt
- domain/src/main/java/com/pocs/domain/repository/AdminRepository.kt
- domain/src/main/java/com/pocs/domain/usecase/admin/CreateUserUseCase.kt
- presentation/src/androidTest/java/com/pocs/presentation/AdminUserCreateScreenTest.kt
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/pocs/presentation/mapper/UserCreateInfoMapper.kt
- presentation/src/main/java/com/pocs/presentation/model/admin/AdminUserCreateUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/admin/UserCreateInfoUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/admin/user/AdminUserFragment.kt
- presentation/src/main/java/com/pocs/presentation/view/admin/user/create/AdminUserCreateActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/admin/user/create/AdminUserCreateScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/admin/user/create/AdminUserCreateViewModel.kt
- presentation/src/main/java/com/pocs/presentation/view/component/dialog/PasswordDialog.kt
- presentation/src/main/java/com/pocs/presentation/view/component/textfield/PocsOutlineTextField.kt
- presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditScreen.kt
- presentation/src/main/res/drawable/ic_baseline_add_24.xml
- presentation/src/main/res/layout/fragment_admin_user.xml
- presentation/src/main/res/values/strings.xml
- test-library/src/main/java/com/pocs/test_library/fake/FakeAdminRepositoryImpl.kt
Resolves #75, resolves #82 
**참고사항**
- 기존에 유저 편집 화면에서 사용하던 텍스트 필드를 재사용했습니다. 이 텍스트 필드의 이름은 `PocsOutlineTextField`입니다. 엔터키 입력을 못하도록 했습니다.
> AdminUserCreate API, UI 구현 

- data/src/main/java/com/pocs/data/api/PostApi.kt
- data/src/main/java/com/pocs/data/model/post/PostDeleteBody.kt
- data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt
- data/src/main/java/com/pocs/data/repository/UserRepositoryImpl.kt
- data/src/main/java/com/pocs/data/source/PostRemoteDataSource.kt
- data/src/main/java/com/pocs/data/source/PostRemoteDataSourceImpl.kt
- domain/src/main/java/com/pocs/domain/repository/UserRepository.kt
- domain/src/main/java/com/pocs/domain/usecase/post/CanDeletePostUseCase.kt
- domain/src/main/java/com/pocs/domain/usecase/post/CanEditPostUseCase.kt
- domain/src/main/java/com/pocs/domain/usecase/post/DeletePostUseCase.kt
- domain/src/main/java/com/pocs/domain/usecase/user/GetCurrentUserTypeUseCase.kt
- domain/src/test/java/com/pocs/domain/CanDeletePostUseCaseTest.kt
- domain/src/test/java/com/pocs/domain/CanEditPostUseCaseTest.kt
- domain/src/test/java/com/pocs/domain/GetUserDetailUseCaseTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/UserDetailActivityTest.kt
- presentation/src/main/java/com/pocs/presentation/mapper/PostDetailMapper.kt
- presentation/src/main/java/com/pocs/presentation/mapper/PostWriterMapper.kt
- presentation/src/main/java/com/pocs/presentation/model/post/PostDetailUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/post/item/PostDetailItemUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/post/item/PostWriterUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/home/article/ArticleFragment.kt
- presentation/src/main/java/com/pocs/presentation/view/home/notice/NoticeFragment.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailViewModel.kt
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/pocs/presentation/PostDetailViewModelTest.kt
- presentation/src/test/java/com/pocs/presentation/UserDetailViewModelTest.kt
- test-library/src/main/java/com/pocs/test_library/fake/FakePostRepositoryImpl.kt
- test-library/src/main/java/com/pocs/test_library/fake/FakeUserRepositoryImpl.kt
resovles #37 
- Post 삭제를 위한 API 연결,
- PostWriterUIstate 생성을 위한 PostDeleteMapper 수정 및 WriterMapper 생성
- ViewModel 기능 구현 과정에서 필요한 CanEditUseCase , CandeleteUseCase 의 생성
- ViewModel 과 Activity에서는 사용자의 권한에 따라 menu가 보이거나 보이지않는 설정 추가
- 삭제가 되었을때, 이전의 Acitvity에서 SnackBar가 보이도록 함
> PostDelete API 구현 및 UI 추가 구현

- data/src/main/java/com/pocs/data/api/PostApi.kt
- data/src/main/java/com/pocs/data/model/post/PostUpdateBody.kt
- data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt
- data/src/main/java/com/pocs/data/repository/UserRepositoryImpl.kt
- data/src/main/java/com/pocs/data/source/PostRemoteDataSource.kt
- data/src/main/java/com/pocs/data/source/PostRemoteDataSourceImpl.kt
- domain/src/main/java/com/pocs/domain/usecase/post/UpdatePostUseCase.kt
- presentation/src/androidTest/java/com/pocs/presentation/PostEditActivityTest.kt
- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditViewModel.kt
- test-library/src/main/java/com/pocs/test_library/fake/FakePostRepositoryImpl.kt
resolves #36 
- Post 편집 API 연결 및 구현하였습니다.
- Post 편집 API 성공시 302 리다이렉션 코드가 전달되기 때문에 반환 값을 [ResponseBody]이 아닌 [Response]로 하였고, 그에 따라 중간중간에 다시 수정을 하였습니다.
- 메뉴의 편집기능의 확인을 위해서 current User의 userId 값을 2-> 1로 변경하였습니다.(ID가 다르면 메뉴에서 편집기능이 안보이기 때문)
- 그에 맞게 테스트 프로그램 또한 변경을 하였습니다.
> Post 편집 기능 API 연결 및 기능 구현 및 보완

- presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
Resolves #111
- 이전 : 기수 3기
- 현재 : 기수 3
> 유저 상세 화면에서 기수 "기" suffix 문자 제거

- data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt
API 문서가 잘못되어 포스트 수정후 성공했을 때 204코드를 반환한다고 잘못되어있어 302코드인 경우를 성공조건으로 수정했습니다.
> 포스트 수정 후 성공 조건을 302 코드가 왔을때로 수정

- data/src/main/java/com/pocs/data/api/UserApi.kt
- data/src/main/java/com/pocs/data/mapper/UserListSortTypeMapper.kt
- domain/src/main/java/com/pocs/domain/model/user/UserListSortingMethod.kt
- presentation/src/main/java/com/pocs/presentation/extension/ContentLoadStateBindingExt.kt
- presentation/src/main/java/com/pocs/presentation/model/user/UserUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/admin/post/AdminPostFragment.kt
- presentation/src/main/java/com/pocs/presentation/view/admin/user/AdminUserFragment.kt
- presentation/src/main/java/com/pocs/presentation/view/home/article/ArticleFragment.kt
- presentation/src/main/java/com/pocs/presentation/view/home/notice/NoticeFragment.kt
- presentation/src/main/java/com/pocs/presentation/view/post/by/user/PostByUserActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/user/UserFragment.kt
- presentation/src/main/res/layout/fragment_user.xml
- presentation/src/main/res/menu/menu_sorting_method_pop_up.xml
- presentation/src/main/res/values/strings.xml
Resolves #124 
- 가입일순으로 정렬하는 기능을 누락해서 추가했습니다.(근데 API 보면 기본 쿼리값이 `null`일때 가입일 순으로 하고 있습니다. 이보다 createdAt을 전달할때 가입을 순으로 정렬하고 이것을 기본값으로 쓰는게 낫지 않을까 생각합니다.)
- 회원 정렬 방법이 바뀌었을 때 최상단으로 스크롤하도록 했습니다.
- 정렬 버튼 색상을 강조하지 않는 색으로 변경하고 클릭 가능한 부분을 좌우 꽉차지 않도록 수정했습니다.
> 유저 목록 정렬 가입순 추가 및 레이아웃 향상

- presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditScreen.kt
- presentation/src/main/res/drawable/ic_baseline_account_circle_24.xml
- presentation/src/main/res/layout/item_user.xml
- 다크모드에서 회원 아이콘의 색상이 잘못된 문제를 수정했습니다.
- 모든 회원의 기본 아이콘을 통일 시켰습니다.
|홈 화면 전|홈 화면 후|
|---|---|
|![image](https://user-images.githubusercontent.com/57604817/183280664-0b7a872b-8cad-47a8-84a1-e7a810f5c7c7.png)|![image](https://user-images.githubusercontent.com/57604817/183280633-074423f4-6d33-4d2d-92b6-7d3165e9ff3b.png)|
|회원 목록|회원 디테일|회원 편집|
|---|---|---|
|![image](https://user-images.githubusercontent.com/57604817/183280725-e64d0b01-311e-4322-989c-6db4e2b5a7e3.png)|![image](https://user-images.githubusercontent.com/57604817/183280754-9b70036c-0852-4318-bb19-a974d36cf02f.png)|![image](https://user-images.githubusercontent.com/57604817/183280756-eba1cfa9-e52d-4969-b76a-bab0692544c3.png)|
> 회원 아이콘 다크모드 색상 문제 해결 및 전체 통일

- domain/src/main/java/com/pocs/domain/usecase/post/AddPostUseCase.kt
- presentation/src/androidTest/java/com/pocs/presentation/PostCreateActivityTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/PostEditActivityTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/PostEditScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/extension/PostCategoryExt.kt
- presentation/src/main/java/com/pocs/presentation/model/BasePostEditUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/post/PostCreateUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/post/PostEditUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateViewModel.kt
- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditViewModel.kt
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/pocs/presentation/PostCreateViewModelTest.kt
- presentation/src/test/java/com/pocs/presentation/PostEditViewModelTest.kt
- test-library/src/main/java/com/pocs/test_library/fake/FakePostRepositoryImpl.kt
Resolves #139 
추가로 PostEditViewModel과 PostCreateViewModel에서 잘못된 상태관리를 수정했습니다. 
수정 전에는 한 번 초기화 된 후 또 다시 초기화 될 수 있었습니다. 이때문에 화면 회전 혹은 시스템을 어두운 테마로 전환시 `initUiState`가 또 호출되어 다시 초기화 되었습니다. 
수정 후에는 다시 초기화 하지 못하도록하여 그대로 상태가 유지됩니다.
> 게시글 작성시 카테고리 고를 수 있는 기능 추가 및 잘못된 상태관리 수정

- data/src/main/java/com/pocs/data/di/NetworkModule.kt
- data/src/main/java/com/pocs/data/model/auth/AuthLocalData.kt
- data/src/main/java/com/pocs/data/repository/AuthRepositoryImpl.kt
- data/src/test/java/com.pocs/data/AuthRepositoryTest.kt
- domain/src/main/java/com/pocs/domain/repository/AuthRepository.kt
- domain/src/main/java/com/pocs/domain/usecase/auth/IsAuthReadyUseCase.kt
- presentation/src/main/java/com/pocs/presentation/model/auth/LoginUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginViewModel.kt
- presentation/src/test/java/com/pocs/presentation/LoginViewModelTest.kt
- test-library/src/main/java/com/pocs/test_library/fake/FakeAuthRepositoryImpl.kt
- test-library/src/main/java/com/pocs/test_library/fake/source/remote/FakeAuthRemoteDataSource.kt
Resolves #144 
AuthRepository에 `isReady`라는 속성을 두어 초기화 되었음을 나타내는 flow를 추가했습니다. 이 플로우를 로그인 뷰 모델에서 collect하여 isReady가 true로 온다면 스플래시 스크린을 제거합니다.
https://developer.android.com/guide/topics/ui/splash-screen#suspend-drawing 을 참고하여 해결했습니다.
> 스플래시 스크린 Auth 초기화 될 때까지 보이도록 수정

- domain/src/main/java/com/pocs/domain/repository/AuthRepository.kt
- presentation/src/main/java/com/pocs/presentation/model/auth/LoginUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginViewModel.kt
- presentation/src/test/java/com/pocs/presentation/LoginViewModelTest.kt
Fixes #150 
앱 실행 후 로그인 되어있는 것을 확인하면 `hideSplashScreen`을 그대로 `false`로 두도록 했습니다. 로그인 되어있는 것을 확인한다면 홈화면으로 전환되어 스플래시 화면이 사라지기 때문입니다.
https://user-images.githubusercontent.com/57604817/184300227-511c5f92-3774-4649-95c7-94c635490d1a.mov
> 로그인 되어있는 상태에서 앱 실행시 로그인 화면 잠깐 보였다 사라지는 문제 해결

- data/src/main/java/com/pocs/data/api/AuthApi.kt
- data/src/main/java/com/pocs/data/di/RepositoryModule.kt
- data/src/main/java/com/pocs/data/mapper/UserCreateInfoMapper.kt
- data/src/main/java/com/pocs/data/model/admin/UserCreateInfoBody.kt
- data/src/main/java/com/pocs/data/model/auth/AuthLocalData.kt
- data/src/main/java/com/pocs/data/model/auth/LoginResponseData.kt
- data/src/main/java/com/pocs/data/model/auth/SessionValidResponseData.kt
- data/src/main/java/com/pocs/data/model/post/PostWriterDto.kt
- data/src/main/java/com/pocs/data/model/user/UserDto.kt
- data/src/main/java/com/pocs/data/model/user/UserUpdateBody.kt
- data/src/main/java/com/pocs/data/repository/AuthRepositoryImpl.kt
- data/src/main/java/com/pocs/data/source/AuthRemoteDataSource.kt
- data/src/main/java/com/pocs/data/source/AuthRemoteDataSourceImpl.kt
- data/src/main/java/com/pocs/data/source/UserRemoteDataSourceImpl.kt
- data/src/test/java/com.pocs/data/AuthRepositoryTest.kt
- domain/src/main/java/com/pocs/domain/model/admin/UserCreateInfo.kt
- presentation/src/main/java/com/pocs/presentation/constant/UserConstant.kt
- presentation/src/main/java/com/pocs/presentation/mapper/UserCreateInfoMapper.kt
- presentation/src/main/java/com/pocs/presentation/model/admin/AdminUserCreateUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/admin/UserCreateInfoUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/admin/user/create/AdminUserCreateScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginScreen.kt
- presentation/src/main/res/values/strings.xml
- test-library/src/main/java/com/pocs/test_library/fake/source/remote/FakeAuthRemoteDataSource.kt
- test-library/src/main/java/com/pocs/test_library/mock/User.kt
Resolves #162 
- 로그인 혹은 세션 검증 API 응답에 유저 정보를 주기로 벡엔드가 수정되어 로그인 혹은 세션 검증 후 중복되는 유저 정보 요청을 제거했습니다.
- userName을 ID로 사용하기로 결정하였기 때문에 이에 맞게 아래처럼 대응했습니다.
- 유저 생성시 userName 입력 창은 "아이디" 라는 문구로 수정
- 유저 정보 수정시 userName이 아닌 name을 수정하도록함
- 유저 정보를 얻어올때 userName이 아닌 name을 얻도록 수정함
**아직 회원 정보를 수정하면 비밀번호가 바뀌는 버그는 존재합니다. 회원정보 수정하지 말아주세요**
> API 업데이트 대응

- presentation/src/androidTest/java/com/pocs/presentation/KeyboardHelper.kt
- presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
아래의 코드에서 키보드를 숨기는 `keyboardController?.hide()` 코드가 호출되고 `controller.hide()`가 호출될 때 테스트에 가끔 실패합니다. 원인을 파악하지 못하였기 때문에 테스트를 불가피하게 수정했습니다.
https://github.com/hansung-pocs/blog-android/blob/e89ed3bd43770e8a4a5dfaa25673d0a05c5b4e90/presentation/src/main/java/com/pocs/presentation/view/component/bottomsheet/CommentModalBottomSheet.kt#L176-L179
KeyboardHelper는 https://github.com/androidx/androidx/blob/androidx-main/compose/foundation/foundation/src/androidAndroidTest/kotlin/androidx/compose/foundation/text/KeyboardActionsTest.kt 에서 구했습니다.
> 불안정한 테스트 수정

- data/src/main/java/com/pocs/data/api/AuthApi.kt
- data/src/main/java/com/pocs/data/di/NetworkModule.kt
- data/src/main/java/com/pocs/data/source/AuthLocalDataSourceImpl.kt
Resolves #179 
OkHttp client에 인터셉터를 추가하여 API 요청할 때마다 세션 토큰이 존재하면 세션 토큰을 포함하도록 수정했습니다.
추가로 `AuthLocalDataSource.getData` 함수가 자주 호출되기 때문에 클래스 변수로 캐싱하여 빠르게 접근할 수 있도록 했습니다.
> 모든 API 요청에 세션 토큰 헤더 포함하도록 수정

- data/src/main/java/com/pocs/data/api/AuthApi.kt
- data/src/main/java/com/pocs/data/di/NetworkModule.kt
- data/src/main/java/com/pocs/data/repository/AuthRepositoryImpl.kt
- data/src/main/java/com/pocs/data/source/AuthLocalDataSource.kt
- data/src/main/java/com/pocs/data/source/AuthLocalDataSourceImpl.kt
- data/src/main/java/com/pocs/data/source/AuthRemoteDataSource.kt
- data/src/main/java/com/pocs/data/source/AuthRemoteDataSourceImpl.kt
- test-library/src/main/java/com/pocs/test_library/fake/source/local/FakeAuthLocalDataSource.kt
- test-library/src/main/java/com/pocs/test_library/fake/source/remote/FakeAuthRemoteDataSource.kt
Fixes #179 
아래의 코드에서 `newRequest = `을 하지 않아 헤더에 토큰이 추가되지 않았습니다.
```kotlin
newRequest = newRequest.newBuilder().addHeader(
name = TOKEN_HEADER_KEY,
value = authLocalData.sessionToken
).build()
```
인터셉터를 통해 토큰이 추가되면 `AuthApi`의 `logout`, `isSessionValid`에서 헤더가 중복됩니다. 때문에 중복되지 않도록 헤더값들을 제거했습니다.
`AuthApi`에 토큰을 전달할 필요가 없어졌습니다. 따라서 `AuthRepositoryImpl`에 token 필드가 필요없어져 제거했습니다.
> 헤더에 토큰 추가하는 로직 문제수정 및 토큰 헤더 중복추가 않도록 수정

- build.gradle
- presentation/build.gradle
- presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/PostEditScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/extension/ContextExt.kt
- presentation/src/main/java/com/pocs/presentation/extension/NumExt.kt
- presentation/src/main/java/com/pocs/presentation/extension/ViewExt.kt
- presentation/src/main/java/com/pocs/presentation/model/post/BasePostEditUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/post/PostCreateUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/post/PostEditUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/component/Markdown.kt
- presentation/src/main/java/com/pocs/presentation/view/component/markdown/MarkdownText.kt
- presentation/src/main/java/com/pocs/presentation/view/component/markdown/MarkdownToolBar.kt
- presentation/src/main/java/com/pocs/presentation/view/post/adapter/PostAdapter.kt
- presentation/src/main/java/com/pocs/presentation/view/post/adapter/PostViewHolder.kt
- presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateViewModel.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditViewModel.kt
- presentation/src/main/res/values-night/themes.xml
- presentation/src/main/res/values/themes.xml
- presentation/src/test/java/com/pocs/presentation/MarkdownToolBarTest.kt
Resolves #187 
마크다운 스타일을 커스텀하기가 상당히 까다로웠습니다..
- `toDp()` extension을 만들어 다른 화면 밀도를 가진 다양한 기기에서 동일한 간격을 적용하도록 했습니다. 이는 Markwon 라이브러리가 Compose로 구현되지 않고 View로 구현되었기 때문에 커스텀시 float와 같은 일반 숫자로 값을 넣어야하기 때문입니다.
- 깃헙 앱과 같은 툴바를 만들어 사용자가 쉽게 마크다운 문법을 적용할 수 있도록 했습니다.
|상세화면1|상세화면2|
|---|---|
|![image](https://user-images.githubusercontent.com/57604817/185868181-76511210-82c5-4375-b187-4d2d0cbc4759.png)|![image](https://user-images.githubusercontent.com/57604817/185868214-095edb78-a714-4a53-859b-df01493c4912.png)|
https://user-images.githubusercontent.com/57604817/185869770-82c9e98c-473c-49f4-81f1-3c70b1dfce86.mov
> 게시글 상세 페이지에 마크다운 지원

- presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/view/component/bottomsheet/OptionModalBottomSheet.kt
- presentation/src/main/java/com/pocs/presentation/view/component/bottomsheet/PocsModalBottomSheet.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
Fixes #192 
- 기존에는 `OptionModalBottomSheet`의 매개변수로 정적인 `option`을 받았기 때문에 댓글마다 버튼을 다르게 보이는것이 불가능했습니다. 이는 `optionBuilder`라는 콜백함수를 전달하도록 하여 댓글마다 다른 옵션메뉴들을 보이도록 했습니다. 예를 들어 내가 작성한 댓글인 경우 편집, 삭제 두 버튼이 모두 보이고, 관리자이지만 내 댓글이 아닌 경우 삭제버튼만 보입니다.
- `OptionModalBottomSheet`를 템플릿을 적용하여 추후에 댓글이 아닌 경우에도 이용할 수 있도록 했습니다.
|관리자이고 남의 댓글일때|나의 댓글일때|
|---|---|
|![image](https://user-images.githubusercontent.com/57604817/186405157-d57459d2-28d7-4409-aca8-7cd55505dca1.png)|![image](https://user-images.githubusercontent.com/57604817/186405180-434e6328-e132-4aa3-aa8b-fb5276c24f06.png)|
> 관리자로 로그인 했을 때 내 댓글이 아닌 댓글은 편집할 수 없도록 수정

- presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/view/component/bottomsheet/CommentModalBottomSheet.kt
Fixes #177 
회귀 테스트는 구현에 실패했습니다... 버그가 존재하는 상태에서 실패를 하는 테스트를 구현하기 어렵네요. #177 처럼 상황을 따라하며 테스트를 만들려 해봤으나 구현할 수 없었습니다. 좋은 방법 있으시다면 의견 부탁드립니다.
https://user-images.githubusercontent.com/57604817/186709874-4a1c5ada-c869-42ad-ae50-80d679c2b3b2.mov
> 댓글 추가 후 댓글 입력 창에 이전에 입력했던 댓글 남아있던 버그 수정

- presentation/build.gradle
- presentation/src/androidTest/java/com/pocs/presentation/HomeActivityTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/UserFragmentTest.kt
- presentation/src/main/java/com/pocs/presentation/model/post/HomeUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/user/UserUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/home/HomeViewModel.kt
- presentation/src/main/java/com/pocs/presentation/view/user/UserFragment.kt
- presentation/src/main/res/values/strings.xml
- presentation/src/test/java/com/pocs/presentation/HomeViewModelTest.kt
Resolves #201 
아예 drawer 버튼을 안보이게 하려 했으나 구현에 실패하여 아래와 같이 비활성화하기로 했습니다.
> 익명 회원의 경우 유저 목록으로 이동하는 버튼 비활성화

- presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
- presentation/src/main/res/values/strings.xml
기존에  필요하지않았던 '필수' 라벨을 삭제하였고, 비밀번호 텍스트 박스에 비밀번호를 감추었습니다.
로그인페이지에 사용되었던 PasswordOutlineTextField를 재사용하였기에 로직에서는 큰 차이가 없습니다.
Resolves #199
> 비회원 계정 생성 페이지 UI수정

- domain/src/main/java/com/pocs/domain/model/post/PostCategory.kt
- presentation/src/androidTest/java/com/pocs/presentation/HomeActivityTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/UserFragmentTest.kt
- presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
- presentation/src/main/java/com/pocs/presentation/view/home/study/StudyFragment.kt
- presentation/src/main/res/values/strings.xml
Resolves #202 
API 응답에서 익명회원이 볼 수 없는 게시글은 자동으로 필터링 되기 때문에 응답으로 주어진 모든 게시글을 열람 가능하도록 수정했습니다. 
또한 이제 필요 없어진 `PostCategory`의 `canAnonymousSee` 속성을 제거했습니다.
> 익명 회원이 API응답으로 주어진 모든 게시글 열람 가능하도록 수정

- presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
Resolves #213 
회원 전용 문구는 색상을 달리하여 눈에 띌 수 있도록했습니다.
> 회원 전용 게시글에는 PostDetailScreen에 "회원 전용" 문구 보이도록 수정

- presentation/src/androidTest/java/com/pocs/presentation/PostEditScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/model/post/BasePostEditUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/component/Chips.kt
- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
Fixes #219 
기존에는 QnA 게시글인 경우 상단의 칩들을 안보이게 했습니다.
수정 후에는 익명 회원인 경우에 상단의 칩들을 안보이게 했습니다.
> 익명 회원일때 게시글 편집화면의 Chips 안보이도록 수정

- presentation/src/androidTest/java/com/pocs/presentation/UserDetailActivityTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/UserDetailScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/model/user/UserDetailUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailViewModel.kt
Fixes #222 
유저 강퇴 후 회원 목록 화면에서 강퇴된 회원이 그대로 남아있던 문제를 해결했습니다.
추가로 강퇴된 익명 회원의 경우 유저 상세보기에서 "강퇴됨" 글자를 아래와 같이 보이도록 했습니다.
> 유저 강퇴 후 회원 목록 화면에서 그대로 남아있던 문제 해결

- presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
Resolves #218 
구현은 되었으나 textField의 사용자 경험이 완벽하지는 않습니다. 그 이유는 compose의 TextField에 https://issuetracker.google.com/issues/192043120 이슈가 존재하기 때문입니다. 
이 이슈를 요약하자면, 스크롤 가능한 레이아웃 내에 textField가 위치한 경우 텍스트 필드를 탭 했을때 키보드가 올라오며 커서가 안보이는 문제입니다. 즉, 해당 커서로 자동 스크롤이 정확히 작동하지 않는 문제가 존재합니다. 또 다른 예로 텍스트 필드에 엔터키를 입력할때 자동으로 커서 위치로 스크롤 되지 않아 불편한 사용자 경험도 있습니다.
그래서 일단 `bringIntoViewRequester`와 `reverseScrolling = true`를 이용하여 임시로 해결책을 두었습니다. 하지만 이는 말그대로 임시 방편이며 추후 안드로이드 팀에서 해당 이슈를 해결하기를 바라야 합니다.
https://user-images.githubusercontent.com/57604817/187182608-b68fe873-8ade-447d-81b9-58f50533da27.mov
> PostEditScreen에서 Body 부분 전체 스크롤 가능하도록 수정

- presentation/src/androidTest/java/com/pocs/presentation/LoginScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
- presentation/src/main/res/values/strings.xml
Resolves #231 
- 임시 계정 생성 문구를 개선했습니다.
- 아래의 동영상과 같은 focus 이동 버그를 해결했습니다.(실제 모바일 기기에서는 문제가 없긴함. 에뮬레이터에서 컴퓨터 키보드로 입력시 발생하고있음)
- 임시 계정 생성하기 화면에서 버튼을 "생성하기"로 간소화했습니다.
https://user-images.githubusercontent.com/57604817/187378310-d63827a7-6ed3-4c9e-85e5-d57e834582a5.mov
> 로그인 화면 UI 개선

- presentation/src/main/java/com/pocs/presentation/view/component/PocsDivider.kt
Fixes #234 
Compose 라이브러리 버전을 수정하고나서 Divider의 색상이 변경된것 같습니다. 아마 라이브러리 내부적으로 Divider 색상이 바뀐것 같아요.
> Compose로 구현된 화면에서 Divider 색상 더 진하게 수정

- presentation/src/androidTest/java/com/pocs/presentation/SearchAppBarTest.kt
Fixes #248 
`shouldDebounceOnSearchEventCorrectly_WhenTypingText` 테스트에서 mainClock을 조종하는 시간을 100 + 200 + 200 = 500(==`searchDebounceDelay`) 으로 테스트를 만들었기 때문에 중간에 디바운스가 한번 더 된것같습니다.
수정후 테스트 결과는 아래와 같습니다.
> 불안정한 SearchAppBarTest 수정

- data/src/main/java/com/pocs/data/di/NetworkModule.kt
- presentation/src/androidTest/java/com/pocs/presentation/UserDetailScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/model/post/PostDetailUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/component/FailureContent.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailViewModel.kt
- presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
- presentation/src/test/java/com/pocs/presentation/PostDetailViewModelTest.kt
Resolves #242 
Compose로 구현한 에러 화면의 코드를 개선했습니다. Exception이 ConnectException인 경우 다른 메시지를 보이도록하여 #242 문제를 해결했습니다.
> Compose로 구현된 화면의 에러 화면 코드 개선

- presentation/src/androidTest/java/com/pocs/presentation/UserEditScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/constant/UserConstant.kt
- presentation/src/main/java/com/pocs/presentation/extension/BitmapExt.kt
- presentation/src/main/java/com/pocs/presentation/model/user/UserEditUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/user/edit/UserEditViewModel.kt
- presentation/src/main/res/values/strings.xml
Resolves #253 
- 이미지 용량을 최대 10MB로 제한했습니다.
- 이미지 너비 및 높이가 3000 이상인 경우 3000으로 축소하도록 하였습니다. 이유는 너무 크기가 큰 이미지의 경우 `trying to draw too large … bytes bitmap` 메시지와 함께 앱 충돌이 발생하기 때문입니다.
> 회원 프로필 이미지 용량 및 크기 제한 추가

- presentation/src/androidTest/java/com/pocs/presentation/AdminUserCreateScreenTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/AnonymousCreateScreenTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/LoginScreenTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/UserEditScreenTest.kt
- presentation/src/main/java/com/pocs/presentation/constant/UserConstant.kt
- presentation/src/main/java/com/pocs/presentation/model/admin/AdminUserCreateUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/auth/LoginUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/user/UserEditUiState.kt
- presentation/src/main/java/com/pocs/presentation/model/user/anonymous/AnonymousCreateUiState.kt
- presentation/src/main/java/com/pocs/presentation/view/admin/user/create/AdminUserCreateScreen.kt
- presentation/src/main/java/com/pocs/presentation/view/component/textfield/PasswordOutlineTextField.kt
- presentation/src/main/java/com/pocs/presentation/view/login/LoginScreen.kt
- presentation/src/main/res/values/strings.xml
Resolves #169 
- 로그인 화면
- 관리자 유저 생성 화면
- 유저 편집 화면
- 익명 회원 생성 화면
로그인 화면은 아래와 같이 비밀번호가 6자 이상이어야지 로그인 버튼이 활성화됩니다. 이외의 생성/편집 화면들은 6자 미만으로 입력시 "비밀번호는 6자 이상입니다." 경고 문구를 보이도록 했습니다.
https://user-images.githubusercontent.com/57604817/189252375-a5c2bd11-8aa6-42e0-9aeb-856f1519ac02.mov
> 비밀번호 최소 6자 이상 입력하도록 수정

- .github/workflows/release_tag.yml
if문을 상단으로 이동하여 Release 커밋이 아닌 경우 action을 아예 실행하지 않도록 했습니다. 이전에는 action은 실행되었으나 release tag를 만들지 않았었습니다.
> if문을 상단으로 이동 in release_tag.yml

- presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
- presentation/src/androidTest/java/com/pocs/presentation/comment/CommentTest.kt
- presentation/src/main/java/com/pocs/presentation/view/component/Comments.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailActivity.kt
- presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
Resolves #292 
오랜만에 개발해봅니다. 간단한 기능을 구현해봤어요.
테스트 코드 작성이 편리하도록 helper method를 추가했습니다. 함수에 매개변수가 추가되면 기존 모든 코드를 수정해야 했기 때문입니다.
https://user-images.githubusercontent.com/57604817/210923716-b756316b-c0d0-453b-8c40-6cc960f958fb.mov
> 게시글 상세 화면에서 회원 이름 클릭시 프로필 화면으로 전환하는 기능 추가
